### ISSUE TITLE
export name `ReactComponent` to help people migrate from create-react-app

### ISSUE THREAD

**Issue by CHOYSEN** [ArnaudBarre/vite-plugin-fast-react-svg#3]
refs https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs

**Comment by timsofteng** [comment]
Second here.
@ArnaudBarre is it possible to implement this fallback?

**Comment by ArnaudBarre** [comment]
I can add this, but on the opposite it would be a lie to make it work like the webpack loader because url is not the same syntax either (and Vite philosophy is to used import syntax to do that, not provide both do tree shaking afterward).

I think it's pretty easy to migrate with a regex CMD+R:
- `import { ReactComponent as ([\S]+) }`
- `import $1`

Without space in curly braces
- `import {ReactComponent as ([^}]+)}`
- `import $1`

Tell me what you think about this migration path

**Comment by timsofteng** [comment]
> I can add this, but on the opposite it would be a lie to make it work like the webpack loader because url is not the same syntax either (and Vite philosophy is to used import syntax to do that, not provide both do tree shaking afterward).
> 
> I think it's pretty easy to migrate with a regex CMD+R:
> 
> * `import { ReactComponent as ([\S]+) }`
> * `import $1`
> 
> Without space in curly braces
> 
> * `import {ReactComponent as ([^}]+)}`
> * `import $1`
> 
> Tell me what you think about this migration path

Thank you for response.
Is it possible to use images like react component? Like `<SomeImage />` in code?

**Comment by ArnaudBarre** [comment]
No Vite is "just" a toolchain, not a meta framework like Next or Gatsby, so there is no image component.
But like in CRA, you can import images and use a raw image tag:
```jsx
import imageUrl from "./myImage.png" // always work in Vite
import mySvgAsUrl from "./mySvg.svg?inline" // with this plugin

...

return <img src={imageUrl} />
```

**Comment by CHOYSEN** [comment]
Thanks your suggestion. We originally hoped to migrate without modifying the source code, but your idea is also operational. Thanks again!
